name: inventox-app
region: ams
services:
- name: inventox-app
  github:
    repo: SEDLopes/inventox-app
    branch: main
    deploy_on_push: true
  build_command: ""
  run_command: ""
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  http_port: 80
  health_check:
    http_path: /api/health.php
  envs:
  - key: DB_HOST
    scope: RUN_TIME
    value: ${inventox-db.HOSTNAME}
  - key: DB_NAME
    scope: RUN_TIME
    value: ${inventox-db.DATABASE}
  - key: DB_USER
    scope: RUN_TIME
    value: ${inventox-db.USERNAME}
  - key: DB_PASS
    scope: RUN_TIME
    value: ${inventox-db.PASSWORD}
  - key: DB_PORT
    scope: RUN_TIME
    value: ${inventox-db.PORT}
databases:
- name: inventox-db
  engine: MYSQL
  version: "8"
  production: false
